channels:
- conda-forge
dependencies:
- build
- bump2version
- coverage
- flake8
- ipykernel
- ipython
- jupyter
- pip>=23.3
- pyright
- Sphinx
- tox
- toml
- twine
- watchdog
- wheel>=0.38.1
- hatch
- hatch-requirements-txt
- pytest
- pytest-cov
- doctest