channels:
- conda-forge
dependencies:
- coverage
- flake8
- ipykernel
- ipython
- jupyter
- pip>=23.3
- pyright
- Sphinx
- tox
- toml
- tomli
- watchdog
- pytest
- pytest-cov
- doctest
- hatchling
- hatch-requirements-txt

