{% set pyproject_toml = load_file_data('pyproject.toml', from_recipe_dir=True) %}
{% set name = pyproject_toml.get('project').get('name') %}
{% set version = load_file_regex(load_file='VERSION', regex_pattern=r"^VERSION = ['\"](^['\"]+)") %}

{% set requirements = load_file_data("environment.yml", from_recipe_dir=True) %}
{% set requirements_build = load_file_data("environment_build.yml", from_recipe_dir=True) %}


package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 0cb9087283aedad01e7a2b02c79c2b6eb9a85e808fec23f6b7c954d5b3871127
  requirements: "requirements.txt"


build:
  noarch: python
  number: 1
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  build:
    {% for dep in requirements_build.get("dependencies") %}
    - {{ dep.lower() }}
    {% endfor %}
  host:
    - pip
    - python
    - hatchling
    - hatch-requirements-txt
  run:
    {% for dep in requirements.get("dependencies") %}
    - {{ dep.lower() }}
    {% endfor %}


about:
  home: https://github.com/vivianleung/genomicspy.git
  license: MIT
  license_family: MIT
  summary: Miscellaneous data science methods