{% set pyproject_toml = load_file_data('pyproject.toml', from_recipe_dir=True) %}
{% set name = pyproject_toml.get('project').get('name') %}
{% set version = load_file_regex(load_file='VERSION', regex_pattern='^VERSION = ["\']([^"\']+)["\']') %}
{% set requirements = load_file_data("environment.yml", from_recipe_dir=True) %}
{% set requirements_build = load_file_data("environment_build.yml", from_recipe_dir=True) %}


package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  git_rev: v0.3.3
  git_url: https://github.com/vivianleung/oddsnends.git

# source:
#   url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
#   sha256: 6d347a9f05452513136d5cf95b0e09e176b4ffff6d29c383e255f0be0ce28126
#   requirements: "requirements.txt"

build:
  noarch: python
  number: 1
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  build:
    {% for dep in requirements_build.get("dependencies") %}
    - {{ dep.lower() }}
    {% endfor %}
  host:
    - pip
    - python
    - hatchling
    - hatch-requirements-txt
  run:
    {% for dep in requirements.get("dependencies") %}
    - {{ dep.lower() }}
    {% endfor %}


about:
  home: https://github.com/vivianleung/oddsnends.git
  license: MIT
  license_family: MIT
  summary: Miscellaneous functions and such